### ISSUE TITLE
[API] Comment aspirer tout pour un nouveau départ ?

### ISSUE THREAD

**Issue by kikan** [ansforge/annuaire-sante-fhir-documentation#111]
Bonjour,

Je voudrais remettre notre base des correspondants à zéro pour être certain de ne pas avoir de décalage avec la vôtre.
Quelle est la meilleure façon de faire ?

En FHIR, c'est extrêmement long (pour récupérer tous les PractitionerRole, j'ai mis 7h), et je suppose que ça charge inutilement vos serveurs.

Avez-vous un moyen de récupérer tout à plat comme dans les anciens formats CSV par exemple ?

Merci

**Comment by mchaabaoui** [comment]
Bonjour @kikan,
A l'heure actuelle, le seul moyen d'initialiser une base avec notre API est de faire une recherche paginée des ressources. 
Par ailleurs, la solution de faire un import de masse via les extractions fichiers puis de basculer sur l'API pour les mises à jour ne fonctionne pas. Il n'y a pas en effet de partage d'identifiant entre les 2 modes. 
Cependant, nous allons étudier la possibilité d'implémenter le [bulk](https://github.com/ansforge/IG-fhir-annuaire/issues/77) dans la prochaine release.

**Comment by kikan** [comment]
Merci pour votre réponse, c'est ce que je pensais.
Est-il possible de reprendre à une certaine page si le process plante (coupure réseau, indispo de l'API, etc...) ou de récupérer les données triées par id croissant pour reprendre après un certain id ?
Ça permettrait de faire par étapes, et de reprendre en cas de souci

**Comment by mchaabaoui** [comment]
En cas de panne, il est possible de reprendre pendant 24h (suivant l'appel de la première page) le lien. 
Le lien next continuera automatiquement la pagination. 
 
2 stratégies : 
•	Soit l'import plante complètement, dans ce cas il faut conserver le dernier "next url" et relancer l'import à partir de là
•	Soit certaines pages ont planté dans ce cas il est possible de les relancer mais que si les urls ont été conservées. 
Les urls sont utilisables sur une durée limitée à 24h. 

Plus d'information sur la technique utilisée dans un document github ici : [annuaire-sante-fhir-serveur/search-consistency.md at main · ansforge/annuaire-sante-fhir-serveur (github.com)](https://github.com/ansforge/annuaire-sante-fhir-serveur/blob/main/docs/technical-notes/search-consistency.md) »

**Comment by kikan** [comment]
Super, c’est bien pensé ! Je vais conserver mes URL pour pouvoir reprendre si besoin. 
Merci !
