### ISSUE TITLE
[MSSanté] Mapping attributs anciennes extractions / ressources profils AS de l’API FHIR

### ISSUE THREAD

**Issue by rmauget** [ansforge/annuaire-sante-fhir-documentation#114]
Bonjour,

Ci-joint un PowerPoint qui présente une analyse du mapping entre les attributs des anciennes extractions actuellement utilisée par MSSanté et leur mapping avec les attributs des ressources des profils AS de l’API FHIR.

Merci de passer en revue ces planches pour signaler les erreurs identifiées, confirmer ou infirmer les éléments surlignés en jaune et indiquer si des équivalents aux attributs des anciennes extractions indiqués dans la dernière planche (n°8) existent ou pas dans les profils AS de l’API FHIR (car aucune information trouvée sur ce sujet).

[MSS_DOC_Mapping attribut Annuaire Mailiz attributs FHIR_v1.0.pptx](https://github.com/ansforge/annuaire-sante-fhir-documentation/files/13390189/MSS_DOC_Mapping.attribut.Annuaire.Mailiz.attributs.FHIR_v1.0.pptx)

**Comment by mchaabaoui** [comment]
Ci joint une mise à jour du PPT : [MSS_DOC_Mapping.attribut.Annuaire.Mailiz.attributs.FHIR_v1.1.pptx](https://github.com/ansforge/annuaire-sante-fhir-documentation/files/13443329/MSS_DOC_Mapping.attribut.Annuaire.Mailiz.attributs.FHIR_v1.1.pptx)
