### ISSUE TITLE
[Documentation] Manque as-mailbox-mss-metadata dans description attribut telecom:mailbox-mss de AS Practitioner

### ISSUE THREAD

**Issue by rmauget** [ansforge/annuaire-sante-fhir-documentation#120]
Dans la page décrivant la ressource [AS Practitioner](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-practitioner.html), dans l'onglet "Snapshot Table", dans la description détaillée de l'attribut telecom:mailbox-mss, il manque le "sous-attribut" as-mailbox-mss-metadata (qui est bien présent dans la description du type  [AS Mailbox MSS Datatype](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-mailbox-mss.html#tabs-snap)

Conseil pour la correction : comme pour la description des ressources AS PractitionerRole et AS Organization, ne pas remettre le détail de l'attribut telecom:mailbox-mss dans la description de la ressource AS Practitioner, mais juste laisser l'attribut telecom:mailbox-mss et son type AS Mailbox MSS Datatype (le détail sera obtenu en cliquant sur le type)

**Comment by mchaabaoui** [comment]
Bonjour @rmauget,
Merci  pour cette remarque pertinente, qui sera prise en compte par nos équipes dans la prochaine version de l'Implementation Guide

**Comment by mchaabaoui** [comment]
<img width="792" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/70761903/76e92d11-25c0-4387-bcb7-5ffb23654b6c">

**Comment by zilliw** [comment]
Bonjour,

Le sous-attribut a bien été rajouté dans la documentation. 

Je clôture le ticket.
