### ISSUE TITLE
[API] un filtrage par attribut est-il possible au niveau de l’API ?

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/annuaire-sante-fhir-documentation#122]
comment restreindre les informations contenues dans les résultats de la recherche à un sous-ensemble d'attributs?

**Comment by mchaabaoui** [comment]
doc mise à jour : https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/documentation/resources/search-params.html#85-header

**Comment by zilliw** [comment]
Bonjour,

Un test a été réalisé et le search param _element fonctionne correctement sur l'ensemble des ressources. Suite aux éléments apportés par @mchaabaoui , je cloture l'issue.
