### ISSUE TITLE
[MSS] Les attributs TELEPHONE/DEMATERIALISATION/RESPONSABLE/DESCRIPTION sont ils disponibles dans l'API en accès libre?

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/annuaire-sante-fhir-documentation#125]
Est ce que ces attributs peuvent être ou non produits dans les profils publics de l’API FHIR?
Pour rappel, la définition de chaque attribut : 
- Description : Description fonctionnelle de la boîte aux lettres.
- Responsable :  Texte libre donnant les coordonnées de la (ou des) personne(s) responsable(s) au niveau opérationnel de la boîte aux lettres. Non renseigné pour les types de boîte aux lettres "PER".
- Dématérialisation  : Indicateur d’acceptation de la dématérialisation (ou « Zéro papier »). 
  - O : Dématérialisation acceptée 
  - N : Dématérialisation refusée.
- Téléphone : Coordonnées téléphoniques spécifiques à l’usage de la boîte aux lettres MSSanté.

**Comment by mchaabaoui** [comment]
Pour info, les attributs responsable et téléphone ne sont plus disponibles dans l'API depuis la version 1.19, faisant suite à une demande de la part du métier.

**Comment by zilliw** [comment]
Bonjour,

Suite à la réponse apportée par Mohammed, je clôture cette issue.
