### ISSUE TITLE
Comment faire des requêtes multicritères / multi ressources en API FHIR ?

### ISSUE THREAD

**Issue by rmauget** [ansforge/annuaire-sante-fhir-documentation#126]
Cf. [MSS_DOC_API FHIR Recherche Multicrières_v1.0.pptx](https://github.com/ansforge/annuaire-sante-fhir-documentation/files/13516824/MSS_DOC_API.FHIR.Recherche.Multicrieres_v1.0.pptx), contient les explications et questions

**Comment by mchaabaoui** [comment]
[MSS_DOC_API.FHIR.Recherche.Multicrieres_v1.1.pptx](https://github.com/ansforge/annuaire-sante-fhir-documentation/files/13561102/MSS_DOC_API.FHIR.Recherche.Multicrieres_v1.1.pptx)

**Comment by rmauget** [comment]
Merci, les réponses sont claires et complètes
