### ISSUE TITLE
[API] Les recherches croisées de type HAS sont elles prises en charge sur le service?

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/annuaire-sante-fhir-documentation#128]
Lorsqu’une requête multicritères porte sur plusieurs critères de différents types de ressources (exemple : recherche sur le nom d’exercice du PS – ressource AS PractitionerRole – et sur le nom de la structure d’exercice du PS – ressource AS Organization), comment construire la / les requête(s) FHIR ?
Est-il possible dans une même requête FHIR d’intégrer des critères sur des ressources de types différents ? Si oui, comment (exemple) ?

**Comment by zilliw** [comment]
Bonjour,

Suite à la réponse apportée par Mohammed, je cloture cette issue.

**Comment by ulyssetsd** [comment]
Je suis développeur chez Weda et je me retrouve dans la même situation. Nous cherchons à remplacer notre dépendance au LDAP de l'ANS par l'API FHIR, mais l'absence de paramètres chaînés nous bloque sur le cas de recherche multi-critères.

Les chained parameters sont définis à la section **§3.1.1.4.15** de la spécification [FHIR R4](https://hl7.org/fhir/R4/search.html#chaining), avec le statut **Normative**. Il ne s'agit donc pas d'une feature optionnelle mais d'une partie obligatoire du standard HL7.

## Cas d'usage bloquant

La requête cible que nous n'arrivons pas à exprimer :

```sh
GET /fhir/v2/PractitionerRole
  ?practitioner.qualification-code=SM26
  &organization.address-city=Paris
  &_include=PractitionerRole:practitioner
  &_include=PractitionerRole:organization
  &_count=10
```

Réponse actuelle : `400 — Parameter practitioner.qualification-code not found for resource PractitionerRole`

## Pourquoi le contournement actuel est impraticable

Sans chaînage, le seul contournement est un waterfall côté client :

1. `GET /Organization?address-city=Paris&_count=50000` → **~42 000 organisations** récupérer
2. `GET /PractitionerRole?organization={batch120}&_count=50000` × **~350 requêtes** → **~108 000 PractitionerRole** récupérer
3. Filtrage en mémoire par spécialité, nom, prénom, etc.

Ce pattern rend la **pagination serveur impossible** : on ne peut pas demander "la page 2 des cardiologues à Paris" sans avoir d'abord chargé l'intégralité des résultats.

## Paramètres concernés

Les ressources `Practitioner` et `Organization` disposent déjà des index nécessaires côté serveur. Il s'agit d'exposer ces paramètres comme cibles de chaînage depuis `PractitionerRole` : `practitioner.qualification-code`, `practitioner.family`, `practitioner.given`, `organization.address-city`, `organization.address-postalcode`, `organization.address`.
