### ISSUE TITLE
Récupérer des données selon une liste de codes de communes

### ISSUE THREAD

**Issue by JeanPierreRod** [ansforge/annuaire-sante-fhir-documentation#136]
Bonjour,

Dans le cadre du projet Territoire d'Innovation et Santé de demain (TI-TSD) entre GrandEnov+, Data GrandEst et l'ASN, nous collaborons pour récupérer des données des organisations (Organizations) et des praticiens liés à ces structures (PractitionerRole + Practitioner) en utilisant une liste de codes de communes.

Nous avons tenté d'obtenir ces données de l'API de l'ASN, mais le résultat obtenu est un fichier JSON au format imbriqué, avec des codes décrivant certaines caractéristiques des praticiens. Nous savons que nous pouvons obtenir ces valeurs en utilisant les liens du "system", mais nous nous demandons s'il est possible d'obtenir ces données sous un format plus lisible.

Quels conseils pourriez-vous nous donner pour atteindre notre objectif ? Merci.

Bien cordialement,
Jean Pierre RODRIGUEZ

**Comment by mchaabaoui** [comment]
Bonjour @JeanPierreRod ,

Tout d'abord, merci pour votre intérêt envers notre API.
Le standard FHIR, sur lequel s'appuie notre implémentation, ne prévoit pas d'autres formats en dehors des formats XML et JSON pour la représentation des données.
Ainsi, les systèmes qui implémentent FHIR doivent absolument prendre en charge  :  
- le modèle de données organisé en objets modulaires appelés ressources et un atterrissage syntaxique sur du XML, JSON ou RDF
- l'implémentation d'une API REST pour la manipulation directe des ressources avec des requêtes HTTP + autres méthodes d’échange

Nos préconisations : 
- on préconise l'utilisation du format JSON plutôt que XML. Actuellement, on propose les deux formats json et xml mais ce dernier sera fort probablement retiré dans la prochaine version de l'API (V2).
- il est possible d'utiliser le paramètre _elements afin de ne récupérer que les données qui vous intéresse (https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/documentation/resources/search-params.html#85-header).
- il convient de consulter les structures définitions (disponibles [ici](https://github.com/ansforge/annuaire-sante-fhir-documentation/tree/main/StructureDefinition)) afin de faciliter votre lecture/compréhension de chaque ressource.

Par ailleurs, des travaux/réflexions  sont en cours à l'ANS pour simplifier le modèle de données FHIR de l'Annuaire santé en améliorant davantage sa  conformité au standard FHIR sous forme de guide d'implémentation (https://interop.esante.gouv.fr/ig/fhir/annuaire/)

En espérant avoir répondu à vos interrogations.
Cordialement

**Comment by zilliw** [comment]
Bonjour,

Suite à la réponse apportée par Mohammed, je clôture cette issue.
