### ISSUE TITLE
Soucis avec ma clé API ? Mes requests ne fonctionnent plus

### ISSUE THREAD

**Issue by william-ordotype** [ansforge/annuaire-sante-fhir-documentation#138]
Bonjour, 

Mes requests à l'API ne fonctionnent plus depuis ce matin, j'ai édité une nouvelle clé et le problème persiste.  

Pourriez-vous m'aider s'il vous plaît ?

Merci

**Comment by mchaabaoui** [comment]
Bonjour @william-ordotype ,

Le service est actuellement en maintenance.
https://status.annuaire-sante.esante.gouv.fr/

**Comment by william-ordotype** [comment]
Merci pour l'information et bon courage à vous
