### ISSUE TITLE
Recherche structure par adresse et chained parameters

### ISSUE THREAD

**Issue by jerkos** [ansforge/annuaire-sante-fhir-documentation#14]
Bonjour,
Je teste actuellement l'api FHIR et ai quelques questions. 

J'essaie de rechercher une ressource Organization à partir de son nom de rue. Or j'ai l'impression que seul le sous champs "city" du champs "address" fonctionne pour la recherche. Est ce correct ?

J'ai aussi essayé de faire des recherches chainées de type (récupérer tous les practitionerRole appartenant à une organization située dans une ville particulière):
`https://gateway.api.esante.gouv.fr/fhir/PractitionerRole?organization:Organization.address:contains=BRUGES`

Mais je n'obtiens aucun résultat. Est ce normal ?
Supportez vous les recherches chainées ?

Merci pour vos réponses

**Comment by mchaabaoui** [comment]
Bonjour,

Effectivement, nous ne supportons pas (à date) les requêtes chaînées.
Le seul moyen de faire la requête en 1 coup pour cette personne est de faire : /Organization?address:contains=BRUGE&_revinclude=PractitionerRole:practitioner

Par contre, c'est un contournement qui ne fonctionne que si l'on ne filtre pas sur PractitionerRole.

En espérant que la réponse soit à la convenance.
Cordialement,

**Comment by jerkos** [comment]
Merci pour la réponse !
Yes c'est dommage, j'aurai voulu effectivement ajouter des filtres sur le practionerRole. :)

J'ai des performances qui sont de l'ordre de 10 secondes sur une recherche par nom de practitioner (`/PractitionerRole?family:contains=balbal`). Est ce normal ? Ou est ce un environnement de préprod / test qui est plus lent ? (je requête l'url suivante `https://gateway.api.esante.gouv.fr/fhir`)

**Comment by mchaabaoui** [comment]
Cette requête est la plus défavorable car le mot n'existe pas et on doit parcourir toutes nos données pour répondre. Comme il s'agit d'un contains c'est encore plus difficile pour le système. Dans ce cas, le temps de réponse peut actuellement être supérieur à 30 secondes. Nous avons prévu une évolution qui permet de ne pas compter les résultats si cela est trop long. Les recherches lentes seront plus rapides mais n'afficheront pas le champs total (nombre de résultats). Il vous restera la possibilité d'afficher le total avec un paramètre _total=accurate (au détriment de la rapidité). Avec cette évolution family:contains=blabla sera toujours lent mais plus rapide. Par contre une recherche pertinente (type family:contains=dupont) sera beaucoup plus rapide.
