### ISSUE TITLE
Nouveau cas d'usage - Jeton VIHF

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/annuaire-sante-fhir-documentation#146]
Ce cas d’usage sera utilisé pour permettre de construire un jeton VIHF.

**Jeton VIHF** : Vecteur d’Identification et d’Habilitation Formelles. Objet technique utilisé dans le cadre de la sécurisation des échanges de données entre SIS. Il porte entre autres les éléments permettant l'identification, l’authentification d’un
organisme ou d’un utilisateur.

**Comment by abreithoff** [comment]
l'idée est d'aider à la constitution des différentes version du jeton 1.0 à 4.0. Cette dernière version contient les données fonction et genre d'activité qui caractérisent les professionnels à rôle. Ces données ne se retrouve pas dans la carte CPS, les éditeurs qui s'appuie actuellement sur la carte CPx sont donc à la recherche de moyen pour retrouver ces informations. le jeton PSC est poussé par l'ANS mais l'API FHIR est également une solution à mettre en avant. La rédaction de ce cas d'usage doit permettre de leur faciliter la tache.

**Comment by zilliw** [comment]
Bonjour,

Je cloture cette issue.
