### ISSUE TITLE
Profession non trouvée dans PractitionerRole

### ISSUE THREAD

**Issue by Bib34690** [ansforge/annuaire-sante-fhir-documentation#149]
Bonjour,
 
Lors de nos recherches via l’API, nous constatons régulièrement que le code profession n’est pas présent dans le partitionerRole que nous récupérons alors que la profession est bien indiquée si nous regardons l’annuaire de santé en ligne (https://annuaire.sante.fr/web/site-pro).
Voici un exemple :
- Nom : QUAGELLI
- Prénom : Luca
- profession: psychologue
 
Dans l’annuaire en ligne nous indiquons :
Qui/quoi : QUAGELLI Luca
Où : 92
Nous trouvons cette personne et sa profession est indiquée.
 
Via l’API, dans le PractitionerRole retourné, le champ Code contient 3 coding mais aucun n’est de type “...TRE-G15-ProfessionSante”.
Lors de nos tests, pour certains professionnels nous trouvons l’information, mais ca semble être une minorité.
Pouvez-vous nous dire si c’est une anomalie de l’API ou si l’information est dans un autre champs ?

Cordialement

**Comment by mchaabaoui** [comment]
Bonjour @Bib34690,

Il s'agit en effet du coding.professionR95
<img width="410" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/70761903/7d8e498b-264e-4384-b58f-c9594e31a124">

Ce coding est associé à la valueSet [TRE_R95-UsagerTitre](https://mos.esante.gouv.fr/NOS/TRE_R95-UsagerTitre/FHIR/TRE-R95-UsagerTitre/TRE_R95-UsagerTitre-FHIR.json)

En cible, c'est la  [JDV-J108-EnsembleFonction-RASS](https://mos.esante.gouv.fr/NOS/JDV_J108-EnsembleFonction-RASS/FHIR/JDV-J108-EnsembleFonction-RASS) qui sera utilisée dans la prochaine version de l'API dite V2.
Cette JDV regroupera les TRE : G15, R95, R94 et R291

<img width="447" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/70761903/3ebfa098-461d-49e1-adb4-db532297bda4">

**Comment by Bib34690** [comment]
Bonjour mchaabaoui ,
Voici ce que j'ai compris :
Actuellement la réponse peut être dans l'un des 4 coding, sans qu'on puisse savoir lequel sera retourné.
Pour trouver le code profession, on doit chercher 1 des 4 coding TRE-G15, TRE-R95, TRE-R94, TRE-R291.

A partir de la version 2, il n'y aura plus que le coding JDV-J108 dont la liste regroupera les 4 listes ci-dessus.

Ai-je bien compris ?
Quand sera disponible la version 2 ?
Pour l'instant, la liste JDV-J108 ne regroupe pas les 4 ci-dessus. Ex.: Orthophoniste n'y est pas alors qu'il est dans TRE-G15.
Est-ce normal ?
Que signifie JDV ?

**Comment by mchaabaoui** [comment]
Bonjour @Bib34690,

Ci-après mes retours.

**Ai-je bien compris ?**
C'est tout à fait ça. 
Actuellement, un code profession doit forcement être présent dans l'un des 4 coding TRE-G15, TRE-R95, TRE-R94, TRE-R291.

**Quand sera disponible la version 2 ?**
il est pour le moment difficile de prévoir des échéances, toutefois les travaux associés nécessiteront une période d’environ 3 mois. le démarrage des travaux est prévue pour T2 2024.

**Pour l'instant, la liste JDV-J108 ne regroupe pas les 4 ci-dessus. Ex.: Orthophoniste n'y est pas alors qu'il est dans TRE-G15.
Est-ce normal ?**
Il s'agit effectivement d'un oubli de la part des équipes ANS en charge des [NOS](https://esante.gouv.fr/interoperabilite/mos-nos/nos). ce sera corrigé au plus vite.

**Que signifie JDV ?**
[JDV](https://esante.gouv.fr/interoperabilite/mos-nos/nos) signifie jeux de valeurs.

**Comment by Bib34690** [comment]
Bonjour mchaabaoui ,
Merci pour ces réponses très claires.

**Comment by Bib34690** [comment]
super, merci mchaabaoui
