### ISSUE TITLE
Assistance suite à la mise à jour de l'annuaire e-santé

### ISSUE THREAD

**Issue by productMedicalib** [ansforge/annuaire-sante-fhir-documentation#150]
Bonjour,

Nous réalisons un import mensuel des kinés, infirmières et sage-femme de l'annuaire santé (en utilisant votre API) cependant lors de notre dernier import en Janvier 2024, nous avons eu l'impression qu'il y avait de nombreuses nouvelles données dupliquées.

Notre besoin est simplement d'avoir un objet unique par professionnels de santé à domicile dans notre base de données.

Exemples :

1. Voici le résultat à ma recherche RPPS 10005536080 sur https://annuaire.sante.fr/

<img width="1004" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/96178635/064d665c-0d15-4282-b0bb-e199c8bf3f93">

Il y a de nombreux résulats pour la même personne. 

2. Voici le résultat à ma recherche RPPS 10106065971 sur https://annuaire.sante.fr/

<img width="1058" alt="image (1)" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/96178635/1a6434c5-5432-4f0c-bb9c-a8e7344ad0c4">

<img width="1335" alt="image (2)" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/96178635/2a8ebe73-6dc4-4505-b906-e1e05baa3030">

Ici, si j'effectue la même recherche sur le portail de l'API FHIR https://portail.openfhir.annuaire.sante.fr/, Claire Kusznir possède :

- un "PractitionerRole/005-4641606-7733415" avec la fonction FON-17 (Collaborateur) présent dans l'organisation "Organization/001-01-1211489"
- un "PractitionerRole/005-4641606-7747964" avec la fonction FON-17 (Collaborateur) présent dans l'organisation "Organization/001-01-1173281"
- un "PractitionerRole/005-4641606-7581905" avec une fonction FON-22 (Remplaçant, intérimaire, intermittent)

"Organization/001-01-1211489" et "Organization/001-01-1173281" ont la même adresse, comment savoir quelle est la bonne organisation, le bon PractitionerRole ?

3. RPPS  : 10108059733 sur https://annuaire.sante.fr/

<img width="1028" alt="image (3)" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/96178635/9995bf7e-a3ac-4697-8445-2ea855d710c9">

Si j'effectue la même recherche sur le portail de l'API FHIR https://portail.openfhir.annuaire.sante.fr/, j'obtiens 3 PractitionerRole différents équivalents aux 3 résultats de ma recherche sur [annuaire.santé.fr](http://annuaire.xn--sant-epa.fr/)

<img width="1303" alt="image (4)" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/96178635/39630d37-7e99-4904-aeba-f028469d0d07">

Ici, 

- "PractitionerRole/005-5072239-7564661" et " "PractitionerRole/005-5072239-7741610" ne diffèrent que par leurs "id" et leurs "lastUpdated". Ils ont la même fonction "FON-42" qui correspond à "Assistant collaborateur".

- "PractitionerRole/005-5072239-7739346" possède une organisation et une fonction ("FON-01" qui correspond à "Titulaire de cabinet") différent des deux autres objets.

Comment pouvons-nous faire la différence entre tous ces objets quasiment identique ?

___

Par ailleurs, est-ce que la documentation des services de l'Etat pour l'annuaire est à jour ? Et est-ce bien celle-ci ?

[https://esante.gouv.fr/sites/default/files/media_entity/documents/annuaire_sante_fr_dsft_extractions_donnees_libre-acces_v2.4.pdf ](https://esante.gouv.fr/sites/default/files/media_entity/documents/annuaire_sante_fr_dsft_extractions_donnees_libre-acces_v2.4.pdf)

- Avez-vous une version de celle-ci en anglais ?
- Ainsi que les autres documents pertinents pour l'usage de l'annuaire ?

Merci pour votre aide, bien cordialement,

**Comment by mchaabaoui** [comment]
Bonjour @productMedicalib,

Merci pour vos commentaires.
Ci dessous mes réponses :  
- Concernant les 2 cas remontés : 10106065971 et 10108059733) :  il s'agit d'un bug. les PR datant de décembre 2023 devaient être publiés mais avec l'attribut active à false 
<img width="554" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/70761903/8111781b-61ae-4cae-b7de-622db8d809e2">

=> Un ticket a été créé dans le backlog produit pour corriger le bug.

- Avez-vous une version de celle-ci en anglais ?
Non, toute la documentation disponible est en français

- Ainsi que les autres documents pertinents pour l'usage de l'annuaire ?
Toute la documentation sur l'API est disponible sur la page dédiée dans le GitHub de l’ANS : https://github.com/ansforge/annuaire-sante-fhir-documentation

<img width="444" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/70761903/d8e46952-b165-4c46-9e06-3f9bb51b3ed8">

**Comment by cmartet** [comment]
Bonjour,

Je rebondis sur ce ticket car nous avons expérimenté un cas similaire.
Nous développons une plateforme de télésuivi d'insuffisance cardiaque, et nous rapatrions les données de l'API AnnuaireSanté de façon périodique afin d'alimenter notre base de données.

En décembre, nous avons rapatrié le Practitioner/003-3510175 avec un PractitionerRole/005-4237981-7295752.
Le 18 janvier, ce practitioner a été mis à jour dans l'API AnnuaireSanté : le PractitionerRole/005-4237981-7295752 a été supprimé au profit du PractitionerRole/005-4237981-7735749.

Vous confirmez que la politique d'obsolescence des PractitionerRole devrait être gérée par la valeur true/false du booléen `active` comme l'indique cette documentation ? [https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/quick-start/api-basics.html](url)
Avez-vous une visibilité sur l'échéance de résolution de ce Bug ?

Merci pour votre réponse et bonne journée.

**Comment by mchaabaoui** [comment]
Bonjour @cmartet,
Je vaudrais tout d'abord m'excuser pour la réponse tardive.
Je confirme que ce bug ait bien été corrigé le 16/01/24  à la suite de déploiement d'un patch correctif.

**Comment by cmartet** [comment]
Bonjour,
Nous avons rencontré ce mois-ci trois autres cas de rôle ayant totalement disparu (dont deux lundi dernier, suite à une synchronisation de nos données avec votre API).

De plus, nous avons également constaté que nous avons des erreurs 404 lorsque l'on recherche par l'ID d'une organization, appel qui fonctionnait très bien par le passé.
Exemple d'une organization : idnst : 1470014556 / Finess : 470014556 / id : 001-01-93341
=> `https://gateway.api.esante.gouv.fr/fhir/Organization/001-01-93341` : 404 notfound
Recherche par finess :
`https://gateway.api.esante.gouv.fr/fhir/Organization?identifier=470014556`
Semble maintenant liée à l'id : 001-01-1411703
`https://gateway.api.esante.gouv.fr/fhir/Organization/001-01-1411703` => 200 ok

Est-ce que cela veut dire que l'ID utilisé chez vous n'est pas constant dans le temps et qu'on ne peut pas se baser dessus de façon fiable ?

**Comment by zilliw** [comment]
Bonjour @cmartet 

Je vous confirme qu'**il n'est pas recommandé d'utiliser l'identifiant technique** car il n'est pas constant, il peut changer dans le cadre de certaines opérations techniques.

A titre d'exemple pour la ressource 'Organization", il est donc préférable de se baser sur des identifiants stables (ex: identifier FINESS).

Bonne journée,

**Comment by zilliw** [comment]
Bonjour,

Suite aux réponses apportées sur le ticket, je clôture l'issue.

Bien Cordialement,
