### ISSUE TITLE
[Documentation]Biding slices Organization.type

### ISSUE THREAD

**Issue by GCHASTIN** [ansforge/annuaire-sante-fhir-documentation#158]
Dans la vue Differential Table : pas de binding pour les slices organizationType et typeEtablissement à la différence des autres slices.
Aussi, dommage que ces slices n'apparaissent pas en sous niveau de l'élément type comme c'est le cas pour les autres éléments slicés.

![2024-01-23_11h23_55](https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/140815492/c15957da-8c8a-45bc-94fb-896999301c8c)

**Comment by GCHASTIN** [comment]
Dans l'IG FrCore pour le profil FR Core Organization Profile slice typeEtablissement : https://hl7.fr/ig/fhir/core/ValueSet/fr-core-core-organization-type

Représentation des slices : 
![2024-01-23_11h44_29](https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/140815492/4d92e74b-462f-4e00-91fa-0372228e1dd7)

**Comment by GCHASTIN** [comment]
Pas de détail des slices spécifiques ajoutées pour ce profil. Seul les slices du profil FrOrganization sont détaillés : 
![Uploading 2024-01-23_12h29_05.png…]()

**Comment by nriss** [comment]
> Dans la vue Differential Table : pas de binding pour les slices organizationType et typeEtablissement à la différence des autres slices. 

Le binding existe bien pour organizationType, il faut regarder dans le snapshot, il est défini au niveau des profils d'InteropSanté
<img width="1012" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/48218773/d20417fa-1caa-4749-855d-a84cd7115732">

Pour typeEtablissement, il n'y a pas de binding défini effectivement
<img width="1041" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/48218773/cd334b82-be97-4bf9-b9bf-ed54bc20e7b2">

- [ ] Définir binding typeEtablissement ?


> Aussi, dommage que ces slices n'apparaissent pas en sous niveau de l'élément type comme c'est le cas pour les autres éléments slicés.

C'est logique ici, car il n'y a pas de différences appliquées aux sous-attributs de type, c'est le fonctionnement du differential du publisher, on ne peut rien faire de ce côté.

**Comment by GCHASTIN** [comment]
@nriss j'ai mis à jour mon commentaire.

**Comment by nriss** [comment]
> @nriss j'ai mis à jour mon commentaire.

Ok, même réponse du coup, c'est le comportement normal du site, comme tu es en differential tu as que les lignes modifiées

**Comment by GCHASTIN** [comment]
La copie d'écran c'est en mode SNAPSHOT TABLE.

**Comment by nriss** [comment]
Ah oui compris! Effectivement, étonnant!

On a eu des choses bizarre également, avec des mappings manquant (pour info @paulineheurtebise)

Je vais regarder mais je pense qu'on pourra pas faire grand chose, il y a sûrement une problématique au niveau du FrOrganization
