### ISSUE TITLE
[Documentation] Alignement sur l'IG Fr Core en cours de travail?

### ISSUE THREAD

**Issue by GCHASTIN** [ansforge/annuaire-sante-fhir-documentation#159]
Il existe un IG Fr Core en cours (en concertation publique jusqu'au 22/01).
https://interop-sante.github.io/hl7.fhir.fr.core/ig/main/index.html

Cet IG est encore au stade de brouillon, il apporte de la cohérence au projet publié sur Simplifier. 
Les url des profiles, ValueSets et CodeSystems changent cependant par rapport au projet publié sur Simplifier. 

Une prochaine concertation sur le sujet de l'annuaire sera t'elle prévue pour s'aligner avec cet IG Fr Core?

**Comment by nriss** [comment]
Il y a une issue à ce sujet : https://github.com/Interop-Sante/hl7.fhir.fr.core/issues/82

De mon côté, je voyais plutôt dans cet ordre là: 
- Retravailler ces ressources côté FrCore pour reprendre ce qui a été fait au niveau de l'annuaire dans une prochaine release
- Rétablir cet héritage une fois FrCore aligné avec l'annuaire

Rétablir l'héritage aujourd'hui me paraît un peu compliqué car on a trop dévié. Par ex, dans FrCore on a toujours deux profils PractitionerRole, alors que l'on a plus qu'un dans l'annuaire --> https://github.com/Interop-Sante/hl7.fhir.fr.core/pull/61).

Ces travaux n'ont pas été initiés côté IS à cause de l'impact, je voulais avoir le retour de l'écosystème avant de les lancer (comme plusieurs sujets où il y a le label `help wanted` ici : https://github.com/Interop-Sante/hl7.fhir.fr.core/issues)

Merci pour ta remarque pertinente, il y a clairement quelque chose à faire ici :)
Très preneur de ton avis sur cette stratégie!

**Comment by abreithoff** [comment]
[like]  Alexis BREITHOFF reacted to your message:
________________________________

**Comment by GCHASTIN** [comment]
Bonjour Nicolas. 
Oui je comprends mieux la problématique. C'est dommage que les concertations/revues d'IG se télescopent.
Effectivement, il faudra mieux revoir les profils Practitioner et PractitionerRole dans IG Fr Core pour aligner avec cet IG.

**Comment by nriss** [comment]
Oui totalement aligné ! On essaie de faire en sorte que l'écosystème soit le plus cohérent possible, mais il y a toujours des contraintes projets / priorités qui font qu'il y a parfois un petit décalage ...

Concernant l'ancienne gestion avec le double PractitionerRole, j'ai toujours trouvé ça vraiment difficile à comprendre pour l'écosystème, je trouve ça vraiment top ce qui a été fait sur l'IG Annuaire, beaucoup plus clair à mon sens !
J'ai hâte de voir ce que l'écosystème en pense pour pouvoir incorporer ces règles génériques à FrCore :)

En tout cas les éditeurs ont deux possibilités aujourd'hui pour décrire les practiciens
- Prendre les profils FrCore
- Prendre les profils annuaire

Je conseillerai plutôt la deuxième option qui sera la modélisation exposée par l'API Annuaire Santé de l'ANS et qui me paraît donc plus simple

**Comment by zilliw** [comment]
Bonjour,

Suite aux réponses apportées, je clôture l'issue. 

A noter que la prise en compte de la nouvelle version de l'IG 1.0.1 sera prévue pour fin d'année 2024.

Bien Cordialement,
