### ISSUE TITLE
Indisponibilité de l'API

### ISSUE THREAD

**Issue by LioVio** [ansforge/annuaire-sante-fhir-documentation#161]
Bonjour,

Le service est actuellement fortement indisponible, les URLs ne répondent plus :
https://portail.openfhir.annuaire.sante.fr/recherche
![image](https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/113995736/09631b28-a923-45a4-bbc4-4b6e400ea9ae)

Le code suivant retourne 9 fois sur 10 un timeout, même en allongeant le timeout de guzzlehttp :
$header = ['ESANTE-API-KEY' => 'ma_cle_api'];
$client = new GuzzleHttp\Client([
    'base_uri' => 'https://gateway.api.esante.gouv.fr',
    'timeout'  => 5.0,
    'headers'  => $header]);

    $response = $client->request('GET', '/fhir/Practitioner?identifier=' . $rpps .'&active=true');
    $practitioners = $parser->parse((string) $response->getBody());

Est-ce lié à une mise à jour en cours ou à une surcharge ou autre ?
Aucun incident n'est signalé.

Deuxième question, pour éviter de créer une autre issue, y a-t-il un nombre maximal de requêtes que l'on peut envoyer par minute par heure ?

Merci, bien cordialement

**Comment by mchaabaoui** [comment]
Bonjour @LioVio,

Le service était effectivement indisponible le 30/01 pendant 6 heures et 3 minutes en raison d'une panne chez notre hébergeur.
Ce lien permet de connaitre l'état de santé de nos services en temps réel : https://status.annuaire-sante.esante.gouv.fr

Concernant la deuxième question, à présent, notre API en sa version bêta est utilisable sans restriction.

**Comment by zilliw** [comment]
Bonjour,

Suite à la réponse apportée par @mchaabaoui, je clôture l'issue.

Cordialement,
