### ISSUE TITLE
 Pagination - There is no Previous, First and Last links in fhir bundle json response. Only self and next link is present

### ISSUE THREAD

**Issue by aparrot89** [ansforge/annuaire-sante-fhir-documentation#162]
https://build.fhir.org/search.html#paginglinks

**Comment by mchaabaoui** [comment]
Hi @aparrot89,
Thank you for reporting this.
Actually, only Next link is implemented.

**Comment by aparrot89** [comment]
Do you think it could be implemented?

**Comment by mchaabaoui** [comment]
Hi @aparrot89, We don't currently have this on our roadmap. We will add this to our backlog but we don't have an ETA on when we would resolve.

**Comment by zilliw** [comment]
Hi,

As Mohammed mentioned, we do not support this feature, and it is not prioritized on the roadmap (due to both complexity and performance concerns).

I am closing this issue.
