### ISSUE TITLE
Next page inaccessible - PractitionerRole

### ISSUE THREAD

**Issue by 00Claire00** [ansforge/annuaire-sante-fhir-documentation#165]
Bonjour,

Il est impossible d'utiliser le lien Next sur les PractitionerRole avec un filtre sur une organisation.
On peut récupérer les informations de la première page uniquement. 

Ce problème a été signalé en Octobre 2023 mais il n'est toujours pas résolu.
https://github.com/ansforge/annuaire-sante-fhir-serveur/issues/13

Je dois récupérer des informations liées à un grand nombre d'organisations et c'est vraiment bloquant.
Pourriez-vous m'aider ?

Exemple :
https://portail.openfhir.annuaire.sante.fr/fhir/PractitionerRole?organization=001-01-104268

Cordialement

**Comment by mchaabaoui** [comment]
https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/59

**Comment by zilliw** [comment]
Bonjour,

Cette anomalie a bien été identifié, nous vous tiendrons informés lorsque ce sujet sera résolu . En raison d'un sujet similaire ouvert https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/59, je clôture cette issue afin de faciliter le suivi.

Cordialement,
