### ISSUE TITLE
Synchronisation Annuaire Santé

### ISSUE THREAD

**Issue by AimeMalcorps** [ansforge/annuaire-sante-fhir-documentation#167]
Bonjour,

Quelle est la fréquence de synchronisation des données entre l'[annuaire santé](https://annuaire.sante.fr/) et l'API ?

Je me retrouve face à des cas où certaines adresses MSSanté de professionnels sont retournées par l'annuaire santé mais pas par l'API.
Je peux vous fournir des exemples si besoin.

Est-ce un bug ou un délais de synchronisation ?

En vous remerciant,

**Comment by mchaabaoui** [comment]
Hello,

ledit patch correctif ayant été déployé hier avec succès, pourriez vous revérifier SVP?

**Comment by zilliw** [comment]
Bonjour, 
Le patch correctif sur les adresses de messagerie a été réalisé. Le problème de synchronisation est résolu.

Je cloture l'issue.
