### ISSUE TITLE
[Documentation] Màj de la page "Couloirs du Ségur" - Nouvelles définitions

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/annuaire-sante-fhir-documentation#169]
Besoin : mettre à jour la page [Couloirs du Ségur] https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/use-cases/segur/uc-segur.html afin de prendre en compte les nouvelles définirons des couloirs ([ci-jointes](https://github.com/ansforge/annuaire-sante-fhir-documentation/files/14633264/Definitions.des.Couloirs.Segur.docx))

**Comment by zilliw** [comment]
Les modifications des pages concerannt les couloirs du Segur ont été prises en compte.

Je clôture l'issue.
