### ISSUE TITLE
Unable to access the Link/URL: https://annuaire.sante.gouv.fr/fhir/StructureDefinition/PractitionerRole-Name

### ISSUE THREAD

**Issue by DineshPolamreddy** [ansforge/annuaire-sante-fhir-documentation#171]
The concern/challenge here is when we tried to open the below URL it shows the site is not secure. We see the below error and want to check if these are restricted sites or will not be accessible to few countries?
URL : https://annuaire.sante.gouv.fr/fhir/StructureDefinition/PractitionerRole-Name
 

Appreciate if you could check and help us here and let us know if we can access this securely. Thank you.

NOTE:
We tried accessing this URL from our local system (hosted in India) and through Virtual Machines (hosted in US) and we are seeing the same error.

**Comment by zilliw** [comment]
Hi,

Thank for your comment. It seems there was a confusion with the URL you were trying to access. The correct URL you should be using is: https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-practitionerrole.html (for Resource Profile Practitioner Role)

There are no geographical restrictions for accessing this site, so you should be able to reach it securely from any location. Please try using this updated link, and you should not encounter the security error you mentioned.

**Comment by DineshPolamreddy** [comment]
Hi Team,

Appreciate for your quick response and sharing me the correct link.

I have raised a new issue, https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/176 on RPPS+ data.

Can you please guide me there. Thank you

Regards,
Dinesh Polamreddy

**Comment by zilliw** [comment]
Hello,

No problem. I am closing this issue.
