### ISSUE TITLE
zero devant Pratitioner.Identifier 

### ISSUE THREAD

**Issue by Bib34690** [ansforge/annuaire-sante-fhir-documentation#174]
Bonjour,

Lorsque nous récupérons le contenu du champ Identifier dans l'objet Practitioner, nous constatons qu'il contient (parfois ?) un zéro devant le N° reel.
Un N° ADELI comporte 9 chiffres, mais celui qu'on récupère dans Identifier en a 10.
Ex. : Isabelle ROBERT orthophoniste à FABREGUES 34690
son N°ADELI est 349102665 mais le N° contenu dans Identifier est 0349102665.
Ce champ peut aussi contenir un N° RPPS qui a 11 chiffres.

Y a t'il 1 règle pour la récupération de ce N° qui explique la présence de ce chiffre devant ?
Doit-on ajouter ce 0 pour la recherche ?

Cordialement,
Didier PECHAIRE

**Comment by zilliw** [comment]
Bonjour,

Tout d'abord merci pour l'intérêt porté à l'API FHIR.

Lors de l'interrogation à la ressource Practitionner, l'identifier renvoie différents types d'identifiants. Dans le cas d'un PS ADELI, il renvoie :
- **Identifiant du Professionnel de Santé** : ce champ correspond à l'identifiant Adeli (349102665)
- **IDNPS (l'identifiant national du PS)** :  ce champ correspond à la concaténation du type d'identifiant (0 = ADELI, 8 = RPPS) + l'identifiant du professionnel de santé

Exemple: si on réalise une requête sur la ressource practitionner avec un paramètre de recherche "Identifier" 349102665, on récupérera donc dans **l'identifier**:
- l'identifiant ADELI dont le code sera "**ADELI**" et la value "349102665"
- l'ID National du PS dont le code sera '**IDNPS**" et la value "0349102665"

Si c'était un identifiant RPPS, l'ID National du PS aurait démarré par 8.

Cordialement,

**Comment by Bib34690** [comment]
Bonsoir williw,
Merci pour cette réponse très détaillée.

**Comment by mchaabaoui** [comment]
A noter que chaque identifier est porté par un "system" : "urn:oid:1.2.250.1.71.4.2.1" pour IDNPS et "http://adeli.fr" pour ADELI.
Ainsi, la recherche par le couple "system" et "code" permet d'affiner davantage les résultats.

Exemples : 
- recherche par numéro ADELI : ../fhir/Practitioner?identifier=http%3A%2F%2Fadeli.fr%7C349102665
- recherche par IDNPS :  ..fhir/Practitioner?identifier=urn%3Aoid%3A1.2.250.1.71.4.2.1%7C0349102665
