### ISSUE TITLE
portail.openfhir.annuaire.sante.fr - souci certificat SSL

### ISSUE THREAD

**Issue by groupecomplus** [ansforge/annuaire-sante-fhir-documentation#175]
Pendant la connexion  à l'API via curl, j'ai des alertes par rapport à l'invalidité de la chaîne des certificats SSL:

```
$ curl --location 'https://portail.openfhir.annuaire.sante.fr/fhir/ ' -vvv
*   Trying 80.78.2.226:443...
* Connected to portail.openfhir.annuaire.sante.fr (80.78.2.226) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self-signed certificate in certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here:[ https://curl.se/docs/sslcerts.html](https://curl.se/docs/sslcerts.html)

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

J'ai pu confirmer le souci avec n'importe quel navigateur  :

```
https://portail.openfhir.annuaire.sante.fr/ 
 Peer’s Certificate issuer is not recognized. 
 HTTP Strict Transport Security: false 
 HTTP Public Key Pinning: false 
```

et avec Postman aussi :

`SSL Error: Self signed certificate in certificate chain`

Le souci persiste aussi en utilisant le header ESANTE-API-KEY avec le token vers n'importe quel endpoint, par exemple `/fhir/Practitioner`.
Je voudrais éviter la désactivation de la vérification des certificats, si possible.

**Comment by zilliw** [comment]
Bonjour,

Merci pour l'intérêt porté à l'API FHIR.  Au vue des informations fournies dans votre précédent message,  pourriez vous renouveler l'appel en utilisant comme api_url : https://gateway.api.esante.gouv.fr/fhir/

Si vous rencontrez des soucis au niveau des certificats, le service est certifié par un certificat de type personne morale SERVEUR émis par l’IGC Santé. Pour permettre l’authentification mutuelle, il est nécessaire que le client installe les autorités de certification racine de l’IGC Santé, disponibles sous http://igc-sante.esante.gouv.fr/PC/.
Pour plus d'informations: 
- https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/quick-start/quick-start.html
- https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/quick-start/api-basics.html

Cordialement,
