### ISSUE TITLE
Access to RPPS+ Data ot RPPS + API Links

### ISSUE THREAD

**Issue by DineshPolamreddy** [ansforge/annuaire-sante-fhir-documentation#176]
Hi Team,

Can you please share the links related to RPPS+? Where can we find certified identity data of healthcare professionals from the RPPS and Adeli directories?

Regards,
Dinesh Polamreddy

**Comment by DineshPolamreddy** [comment]
I found out that the columns are divided in 3 groups : [Nomenclatures des objets de santé | Agence du Numérique en Santé (esante.gouv.fr)](https://esante.gouv.fr/interoperabilite/mos-nos/nos)

![MicrosoftTeams-image (18)](https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/141801679/71f98975-3588-45d2-a825-158d890fda57)

**Comment by zilliw** [comment]
Hello,

Below is the link concerning RPPS+ (link in French: https://esante.gouv.fr/produits-services/portail-rpps-plus).
Healthcare professionals can come from the RPPS+ directory or from ADELI. To retrieve this information via the FHIR API, you need to query the Practitioner and PractitionerRole resources.

Below is a page with an explanatory diagram linking the concept of Health Object Models - Modèle des Objets de Santé (MOS) and FHIR resources:
https://interop.esante.gouv.fr/ig/fhir/annuaire/

For more information on the MOS, below is a file explaining this MOS modeling:
https://esante.gouv.fr/Mod%C3%A8le-des-objets-de-sant%C3%A9

Best regards,

**Comment by DineshPolamreddy** [comment]
Hello,

Thank you for the quick response and providing the details.

Below are couple of questions:

1. While accessing the Practitioner Role and Practitioner details through API Link (https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/documentation/resources/practitioner-role.html) we are seeing only few records of the Practitioner information around (59 KB). Is this covering all the Practitioners information. 
Attached Image.
![Practitioner API](https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/141801679/94f2b799-a4ea-4982-a1c5-950ad8980996)

2. Attached is the excel, basically this is the column information we are looking for? I mean we need these details for the Practitioners, appreciate if you could help us or navigate to the right API for these details.

[Attributes information needed for Practitioner data.xlsx](https://github.com/ansforge/annuaire-sante-fhir-documentation/files/15184523/Attributes.information.needed.for.Practitioner.data.xlsx)

3. On the FHIR folder page Link: https://mos.esante.gouv.fr/NOS/ there are 500 + folders and we are finding difficulties to identify which ones we need to pick up for fetching the details mentioned in the point 2 attached sheet. Can you please help us here too. 

Your patience and support are highly appreciated. Thank you.

Regards,
Dinesh Polamreddy

**Comment by DineshPolamreddy** [comment]
Hi Team,

Can you please update us here. Thanks

**Comment by zilliw** [comment]
Hello @DineshPolamreddy 

Sorry for the late response.

The information in your file is primarily located in the "Practitioner" and "PractitionerRole" resources. Some information such as the type of expertise (libellé type savoir faire) or type of activity label (libellé genre activité) are not present in the JSON response. However, you can retrieve this information from the Reference Tables (TRE - Table de REference) or Value Sets (JDV - Jeux De Valeurs) specified in the JSON response under the "system" attribute.

_For example, in the PractitionerRole, the associated JDV for the type of activity is https://mos.esante.gouv.fr/NOS/TRE_R23-ModeExercice/FHIR/TRE-R23-ModeExercice_

You can find this information on the system URL particularly in the Implementation Guides provided in the Snapshot Table tab.
![ig](https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/48889931/06d41418-8723-434b-885e-c7fc3a9d7947)
Please note that there are two versions:

- https://interop.esante.gouv.fr/ig/fhir/annuaire/0.1.0/ which is the current version of the API (which is in beta mode) - version 0.1.0 of the IG
- https://interop.esante.gouv.fr/ig/fhir/annuaire/ which is the target version IG2 and on which the technical team is currently working.

I hope I have provided clear answers to your questions.

Best regards,

**Comment by zilliw** [comment]
Hello,

Following the responses provided, I am closing the ticket.

Best regards,
