### ISSUE TITLE
service practitioner - data manquantes ?

### ISSUE THREAD

**Issue by Juldub** [ansforge/annuaire-sante-fhir-documentation#181]
Bonjour,

Nous sommes en train de regarder l'API : https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition/as-practitioner
Et lorsque nous requêtons pour le professionnel suivant : RPPS = 10108808378
Appel suivant : 
 https://portail.openfhir.annuaire.sante.fr/fhir/Practitioner?identifier=10108808378

Alors dans la réponse obtenue nous n'avons pas accès à la plupart des infos, telles que  : 
Prénom, Nom, adresse postale par exemple. 

Quand on interroge l'annuaire, on retrouve bien les informations: 
![image](https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/63001218/be07e81d-cdd8-4ebd-b655-9284aeeebca5)

Dans le fichier PS_LibreAcces_Personne_activite_202405230835 je vois bien les infos aussi :
![image2](https://github.com/ansforge/annuaire-sante-fhir-documentation/assets/63001218/a0f9a921-8b12-43b7-b4f1-ab6f72ffbb3e)

Est-ce normal ? Comment faire pour récupérer plus d'informations ? 

Merci

**Comment by zilliw** [comment]
Bonjour,

Merci pour l'intérêt porté pour l'API FHIR Annuaire Santé.

Des exemples ont été donnés sur notre site sur la page suivante: 
https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/documentation/advanced/link.html

Je vous invite à consulter les cas suivants:
- pour récupérer le code postal d'une Organization liée à un PractitionnerRole, vous pouvez suivre l'exemple 1 en utilisant l'option de recherche include: **Trouver l’Organization et le Practitioner d’un PractitionerRole**

- pour récupérer des informations concernant le prénom et nom d'exercice, vous pouvez suivre l'exemple 2 en utilisant l'option de recherche revinclude **Trouver le nom, le prénom, la civilité, l’adresse postale et les adresses MSS d’un Practitioner en partant de son identifiant ADELI/RPPS**

Cordialement,

**Comment by zilliw** [comment]
Bonjour,

Suite à la réponse apportée à ce ticket, je clôture l'issue.
