### ISSUE TITLE
Code source annuaire-sante-fhir-serveur

### ISSUE THREAD

**Issue by fliot** [ansforge/annuaire-sante-fhir-documentation#20]
Bonjour,

Le README.md indique tel quel la référence au projet
```
Code source : https://github.com/ansforge/annuaire-sante-fhir-serveur/
```

Ce projet n'existe pas/ou plus.
Une idée de où retrouver celui-ci ?

Cdt.

**Comment by fliot** [comment]
Très volontiers,
Mon compte github : https://github.com/fliot
Bien cordialement.

**Comment by mchaabaoui** [comment]
C'est fait. 
vous pouvez désormais y accéder en "Triage role"
