### ISSUE TITLE
API indisponible

### ISSUE THREAD

**Issue by LioVio** [ansforge/annuaire-sante-fhir-documentation#201]
Bonjour,
L'API ne répond plus, exemple : https://portail.openfhir.annuaire.sante.fr/recherche
Est-ce de nouveau un problème d'hébergeur ?
Merci

**Comment by yonnath** [comment]
Même problème constaté ici, API down depuis hier ?

**Comment by NicoRiri** [comment]
Down depuis hier vers 15h pour ma part, dans les jours antérieurs il y avait aussi des soucis de connexion instable.

**Comment by NicoRiri** [comment]
Incroyable ça fonctionne merci beaucoup ! Ça fait une bonne alternative le temps de la panne dommage que les link.relation "next" soit des urls complètes avec le lien gateway et pas seulement des paths / query params mais on va faire avec le temps de

**Comment by LioVio** [comment]
Chez moi, cela ne corrige pas le problème, la connexion est refusée dans les 2 cas (avec 2 clés API différentes) :
- PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: Connection refused for URI https://gateway.api.esante.gouv.fr/fhir/Practitioner?identifier=10101170610
- PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: Connection refused for URI https://portail.openfhir.annuaire.sante.fr/fhir/Practitioner?identifier=10101170610

**Comment by NicoRiri** [comment]
Ton deuxième lien sans utiliser le gateway fonctionne pour moi avec ma clé API.
Le problème que tu rencontrais sur le premier lien est juste que le serveur ne répondait pas.
Sur le deuxième lien s'il te renvoie bien l'erreur :
`{"message":"You're not allowed to access this resource","http_status_code":403}`
C'est que ton api key n'est pas bonne ou que tu ne l'as pas mise dans le bon header;

Possible de voir ta requête AJAX ?

**Comment by LioVio** [comment]
En supprimant la vérification du certificat SSL (qui est auto signé...), et avec  l'URL fournie par Paturages (merci!), j'arrive de nouveau à me connecter à l'API.
Voici la commande du client Guzzle en php ($header contient uniquement la clé API) :
```
$client = new GuzzleHttp\Client([
    'base_uri' => 'https://portail.openfhir.annuaire.sante.fr/', //'https://gateway.api.esante.gouv.fr/',
    'timeout'  => 5.0,
    'headers'  => $header,
    'verify'   => false]);
```
