### ISSUE TITLE
Synchronisation entre API et Annuaire Santé

### ISSUE THREAD

**Issue by AimeMalcorps** [ansforge/annuaire-sante-fhir-documentation#220]
Bonjour,

Il semble qu'il y ai un décalage de synchronisation entre l'API Fhir et l'Annuaire santé au niveau des adresses Mssanté.

Un cas d'exemple est le Practitioner/003-206635 qui dispose d'une adresse Mssanté dans l'Annuaire mais pas depuis l'API.
(https://annuaire.sante.fr/web/site-pro)
Aucune adresse Mssanté n'est retournée lors de l'appel de ce praticien.

Pourriez-vous me donner des éléments sur le fonctionnement de la synchronisation avec l'Annuaire Santé ?

En vous remerciant.

**Comment by AimeMalcorps** [comment]
Bonjour,

Merci pour votre réponse.

Toutes ces règles ont l'air de brider grandement l'outil.

Il me semble dommage que l'API ne permette pas de retrouver les mêmes valeurs que sur l'Annuaire Santé, car sur le terrain, c'est le besoin exprimé par les utilisateurs.

J'ai fais tester l'API à une collège secrétaire, et après plusieurs cas d'utilisation sa remarque a été la suivante : 

 _"Si je dois quand même aller sur l'Annuaire Santé pour vérifier l'existence d'adresses MSSanté des praticiens, alors à quoi sert l'API ?"_

Je n'ai pas su quoi lui répondre.

Si je vous fais ce retour c'est pour tenter de comprendre et d'améliorer le service proposé.

Cordialement,

**Comment by zilliw** [comment]
Bonjour,

Nous sommes actuellement en phase de refonte sur le portail Annuaire Santé. Nous ferons en sorte que les résultats de l'API FHIR soient conforme à ce que l'on retrouve sur l'Annuaire Santé.

Merci en tout cas pour les remontées.

**Comment by zilliw** [comment]
Bonjour,

A la différence de l'API FHIR Annuaire, le Portail Annuaire Santé est un site qui existe depuis plusieurs années. Les API ne sont pas identiques mais l'objectif est de converger vers une seule API (API FHIR Annuaire Santé), d'où certaines différences et que l'on corrigera.

Je clôture ce sujet.

Cordialement,
