### ISSUE TITLE
Bac à sable ?

### ISSUE THREAD

**Issue by EwenQuim** [ansforge/annuaire-sante-fhir-documentation#232]
Y a-t-il un environnement de Bac à Sable de l'API, avec de fausses données ? Ou il existe seulement une API avec toutes les vraies données de l'annuaire Santé ?

Cela nous permettrai d'utiliser de fausses données dans notre environnement "beta".

**Comment by zilliw** [comment]
Bonjour,

Il n'existe aujourd'hui pas d'environnement bac à sable de l'API avec de fausses données. Le seul environnement disponible est l'environnement avec les données de production avec les données publiques.

Bien Cordialement,

**Comment by EwenQuim** [comment]
Merci !
