### ISSUE TITLE
Bulk search (bundle) pour le POST

### ISSUE THREAD

**Issue by DooM3P** [ansforge/annuaire-sante-fhir-documentation#235]
Bonjour,

Merci pour la mise à dispo de votre API.

J'ai vu que l'on pouvait faire des requêtes POST pour rechercher un certain nombre de Practitioners (par exemple)

Mais quand j'envoie ça en batch (ou transaction) en POST avec Postman sur `https://gateway.api.esante.gouv.fr/fhir/` (avec mon header qui marche déjà bien en GET) :
```
{
  "resourceType": "Bundle",
  "type": "batch",
  "entry": [
    {
      "request": {
        "method": "GET",
        "url": "Practitioner/003-5858631"
      }
    },
    {
      "request": {
        "method": "GET",
        "url": "Practitioner/003-5859645"
      }
    }
  ]
} 
```

J'obtiens ça :

```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-0334: Access denied by default policy (no applicable rules)"
        }
    ]
}
```

Dans la doc et une  [issue](https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/127) il est dit que POST fonctionne en lecture..

Mon objectif final, c'est chercher les practitionerRole qui on une organization dans un département donné, en faisant une requête sur Organization et _revinclude puis récupérer ces Roles, extraire leur Practitioner ID et réinterroger l'API (une seule fois, en bundle avec POST). Ca à l'air d'être évoqué à la fin du [usecase](https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/use-cases/full/uc-full.html)

Si ça ne marche pas en POST, il me faudrait soit tout stocker en local, soit faire x requêtes distinctes pour x practitioners, soit une requête GET avec des AND (solution limitée à un petit nombre d'ID).

Merci de votre aide. Je travaille avec Python (j'aime pas Java :P) et Postman.

**Comment by zilliw** [comment]
Bonjour,

Merci pour l'utilisation de l'API ainsi que votre retour. Je vous fais parvenir le retour de l'équipe technique : 

L’api ne supporte pas les transactions pour la recherche. Le POST supporté est avec des paramètres standard (fonction /fhir/Practitioner/_search). Cela est principalement utile si des données de recherche sont sensible ou s’il y a beaucoup de paramètres. 
 
Pour répondre à votre besoin vous aurez besoin de faire tout de même plusieurs requêtes mais vous pouvez le faire en mémoire page par page :
 
- Récupérer les PractitionerRole : https://gateway.api.esante.gouv.fr/fhir/Organization?_revinclude=PractitionerRole:organization&type=GEOGRAPHICAL-ENTITY&address-postalcode=33
 - Récupérer les ids et des Practitioner dans un tableau par exemple puis faire la requête : 
[https://gateway.api.esante.gouv.fr/fhir/Practitioner?_id=003-4511717,003-4658236,003-4591806](https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgateway.api.esante.gouv.fr%2Ffhir%2FPractitioner%3F_id%3D003-4511717%2C003-4658236%2C003-4591806&data=05%7C02%7Cguillaume.pouleriguen.external%40eviden.com%7C7bf2e5c0528442fc58a908dcc5aeeceb%7C7d1c77852d8a437db8421ed5d8fbe00a%7C0%7C0%7C638602602305676005%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=m9e84A2E6hCIPzUu85Bkvfq7LtWCjdUb%2F8KZANGY21k%3D&reserved=0),...
- Ajoutez vos Ids de Practitioner séparés par des virgules. 

Avec cette technique pensez à avoir des tailles de page raisonnable dans la récupération (paramètre _count). 
Si l’url est trop longue, alors vous pouvez le faire en POST avec : 
- POST https://gateway.api.esante.gouv.fr/fhir/Practitioner/_search
- Corps de la requête en url encoded : _id=003-4511717,003-4658236,003-4591806,...

Bien Cordialement,

**Comment by zilliw** [comment]
Bonjour,

Suite à la réponse apportée, je cloture cette issue.

**Comment by DooM3P** [comment]
Merci finalement j'ai tout stocké en local et je récupère les updates pour mettre à jour ce qui m'intéresse
