### ISSUE TITLE
Count total des resultats et existe t'il des quotas ?

### ISSUE THREAD

**Issue by zozo33** [ansforge/annuaire-sante-fhir-documentation#237]
Bonjour 
J'ai besoin de récupérer tous les professions avec un role 10 par paquet de 5000
curl --location 'https://gateway.api.esante.gouv.fr/fhir/v1/PractitionerRole?role=10&active=true&_count=5000' 

Le lien next est bien présent mais j'aimerai connaitre le nombre total d'enregistrement avec un role à 10 et active à true

Mon but est ensuite d'appeler unitairement chaque ligne retournée comme suit : 
curl --location 'https://gateway.api.esante.gouv.fr/fhir/v1/PractitionerRole?practitioner=003-255329&active=true&_include=PractitionerRole%3Apractitioner&_include=PractitionerRole%3Aorganization' 

Est-ce possible, y a t'il des quotas ?
Merci d'avance

**Comment by zilliw** [comment]
Bonjour,

Tout d'abord merci pour l'utilisation de l'API et votre retour. Je vous fais part du retour de l'équipe technique suite à vos questionnements:
- L’affichage par défaut du total dépend du temps d’exécution des requêtes. Si vous souhaitez le forcer, ajoutez le paramètre : « _total=accurate »


Vous trouverez plus d’informations ici : 

[https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/guide/version-1/resources/search-params.html#82-header](https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fansforge.github.io%2Fannuaire-sante-fhir-documentation%2Fpages%2Fguide%2Fversion-1%2Fresources%2Fsearch-params.html%2382-header&data=05%7C02%7Cguillaume.pouleriguen.external%40eviden.com%7C7bf2e5c0528442fc58a908dcc5aeeceb%7C7d1c77852d8a437db8421ed5d8fbe00a%7C0%7C0%7C638602602305659508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Dlj%2FYCfJvp5NjM6aekZg5P0IKGSAXQy%2BRNHQXRiqyeo%3D&reserved=0)
 
Section : 8.2) Paramètre “_total”

Bien Cordialement,

**Comment by zilliw** [comment]
Bonjour,

Suite à la réponse apportée, je cloture cette issue.

Bien Cordialement,
