### ISSUE TITLE
Erreur dans le Guide de l'annuaire de santé

### ISSUE THREAD

**Issue by BenkhoEsea** [ansforge/annuaire-sante-fhir-documentation#240]
Bonjour,

J'avais remarqué une erreur en parcourant le site de l'annuaire de santé comportant les paramètres des ressources utilisées.

Sur la page concernant la ressource PractitionerRole : https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/guide/version-1/resources/practitioner-role.html

Il y a une erreur sur le **4.1) Rechercher tout** : GET [base]/PractitionerRole
GET [base]/Organization&?_include=PractitionerRole:organization #inclure les Organization qui sont référencées par les PractitionerRole (PractitionerRole + Organization)
GET [base]/Organization&?_include=PractitionerRole:practitioner #inclure les Practitioner qui sont référencés par les PractitionerRole (PractitionerRole + Practitioner)
GET [base]/Organization&?_include=PractitionerRole:*

Normalement ça devrait être GET [base]/Organization?_revinclude=PractitionerRole:organization et non des include et sans le &.

Merci à vous de corriger ce passage du guide par avance afin d'éviter les confusions pour les nouveaux (dont moi ^^). 

Cordialement,

**Comment by nriss** [comment]
J'ai transféré dans le bon repo :)

**Comment by zilliw** [comment]
Bonjour @BenkhoEsea ,

Merci d'utiliser l'API FHIR et merci pour cette remontée. Je viens de corriger à l'instant cette coquille au niveau de la documentation.

Je clôture cette issue.

Bien Cordialement,
