### ISSUE TITLE
Organizations et practitioners manquants

### ISSUE THREAD

**Issue by BiomanRouge** [ansforge/annuaire-sante-fhir-documentation#246]
Bonjour,
Je dois récupérer l'ensemble des médecins du travail ainsi que leur département, et je me rends compte que certains des practitionerRoles retournés ont bien une référence vers une organization, mais que celle-ci est inexistante.
Est-ce que cela répond à une règle quelconque, où est-ce que ces organizations devraient également être retournées ?

Voici les identifiants des organizations concernées :
001-01-1097177, 001-01-1095949, 001-01-1091782, 001-01-1427066, 001-01-1096172, , 001-01-1091779, 001-01-1370015, 001-01-1091731, 001-01-1092980, 001-01-1093758, 001-01-1282156, 001-01-1369891, 001-01-1362653, 001-01-1369540, 001-01-1091700, 001-01-1369648, 001-01-1092297, 001-01-1096433, 001-01-1098443, 001-01-239084, 001-01-1096045, 001-01-790185, 001-01-1093010, 001-01-1092976, 001-01-38818, 001-01-1369484, 001-01-1097808, 001-01-1096047, 001-01-1097826, 001-01-1109961, 001-01-1097195, 001-01-1369534, 001-01-582653, 001-01-1091853, 001-01-1426978, 001-01-1096091, 001-01-1096416, 001-01-1096413, 001-01-1097855, 001-01-1108777, 001-01-1370156, 001-01-1370037, 001-01-1093774, 001-01-130393, 001-01-1093778, 001-01-64400, 001-01-1397935, 001-01-1114371, 001-01-1096108, 001-01-1091861, 001-01-1096190, 001-01-1101085, 001-01-1426945, 001-01-1427068, 001-01-162147, 001-01-1427064, 001-01-1097841, 001-01-1091763, 001-01-1115513, 001-01-1091936, 001-01-1370029, 001-01-1369936, 001-01-1092296, 001-01-1097797, 001-01-1109216, 001-01-174289, 001-01-1369827, 001-01-1500531, 001-01-1500559, 001-01-1500530, 001-01-1500516, 001-01-1369385, 001-01-1096123, 001-01-1369842, 001-01-1097227

Il en va de même pour certains practitioners :
003-1684627, 003-282745, 003-216541, 003-494572, 003-316897, 003-124791, 003-160156, 003-395552

Auriez-vous une explication ?

En vous remerciant

**Comment by zilliw** [comment]
Bonjour @BiomanRouge,

Tout d'abord désolé pour le temps de réponse tardif.  Pourriez vous me transmettre:
-  quelques ID techniques des PractitionerRoles que vous appelez et qui font des liens à des organization ou des Practitioners inactifs? 
- l'appel que vous réalisez 

Merci par avance pour votre retour.

Cordialement,

**Comment by BiomanRouge** [comment]
Bonjour @zilliw,

Merci de votre réponse, voici quelques ids (j'en ai 614 en tout) : 

005-451965-4581612, 005-408418-4544337, 005-464669-4745102, 005-182446-7793037, 005-3376209-6616285, 005-421639-5040393, 005-1673509-5212680, 005-475493-4544465, 005-291157-5579516, 005-187505-6693509, 005-126324-5041035, 005-408845-5186391, 005-294765-4576040, 005-230355-7531303, 005-178814-5039264, 005-188878-4267654, 005-147442-1978626, 005-466237-6858317, 005-199024-2582940, 005-5296918-7313595, 005-328945-5544011, 005-112955-5801859, 005-194864-6910244, 005-149530-445523, 005-348550-2175227, 005-348550-2174214, 005-146491-5056419, 005-459272-4400827, 005-3008941-3777399, 005-248832-3886988, 005-185789-2447877, 005-134150-435810, 005-172371-4331092, 005-278280-413575, 005-440743-6641102, 005-213663-2584538, 005-223432-5580470, 005-424480-4164047, 005-3612348-5874630, 005-279492-2490215, 005-3655818-4809989, 005-106476-614745, 005-165676-2008466, 005-127010-682622, 005-183177-5212528, 005-199930-374214, 005-199930-233613, 005-350808-7672086, 005-408315-4416950, 005-5587202-7785465, 005-230192-5035714, 005-184211-2283289, 005-321298-2186520, 005-173687-3809528, 005-313732-5775298, 005-465736-508316, 005-191688-3645937, 005-180532-5787373, 005-3629947-6546789, 005-423258-5815983, 005-186485-3841673, 005-3772828-5008079, 005-195952-5702043, 005-191380-3817969, 005-476994-532628, 005-141198-189810, 005-5187079-7099190, 005-1961336-2658633, 005-475517-525435, 005-1591389-1881430, 005-476874-2482893, 005-157066-596919, 005-450466-2542083, 005-156275-206875, 005-436536-3781745, 005-143907-192600, 005-189442-2472475, 005-1649332-5864497, 005-182850-4147501, 005-184244-3890577, 005-182529-5191642, 005-100623-4690077, 005-440740-5040753, 005-423617-4845131, 005-3388784-4896308

Voici l'appel : 
https://gateway.api.esante.gouv.fr/fhir/v1/PractitionerRole?role=FON-29&_include=PractitionerRole:practitioner&_include=PractitionerRole:organization

Cordialement,

**Comment by zilliw** [comment]
Bonjour @BiomanRouge,

Je vous prie de m'excuser pour le délai de réponse à votre message.

Après analyse, il s'avère que les identifiants techniques ne sont pas pérennes. Voici un exemple pour illustrer la problématique liée à la disparition des ID techniques :

- Prenons l'exemple de la ressource Practitioner. Une ressource de type Practitioner (Professionnel), avec un ID technique, est en statut active.
- Si ce Practitioner devient inactif, son statut passe à false.
- Vous pouvez effectuer une recherche sur cet ID technique, mais il indiquera uniquement que le Practitioner est false, et les informations remontées par l’API seront alors limitées.

Dans le cas où une de nos opérations techniques nécessiterait une réinitialisation de la base de données :
- Les identifiants techniques des **ressources actives** pourraient être modifiés.
- Les **ressources inactives** (statut false) ne seraient plus accessibles dans vos appels, si vous utilisez uniquement les identifiants techniques.

Pour éviter ce problème, nous vous recommandons d'utiliser l'identifier (identifiant métier), qui simplifiera vos recherches et assurera une meilleure continuité.

Par ailleurs, sachez que nous travaillons actuellement sur une nouvelle version de l'API FHIR (V2), dans laquelle un identifiant métier sera intégré directement au niveau de la ressource PractitionerRole.

Bien cordialement,
