### ISSUE TITLE
Connexion Gigya x API ANS

### ISSUE THREAD

**Issue by ouzits** [ansforge/annuaire-sante-fhir-documentation#251]
Hello
Bonjour,
Je me présente, je m’appelle OUZIT Sophia, et je travaille dans le département digital du groupe Danone.
Pour certaines de nos marques, nous travaillons avec des professionnels de la santé, qui ont accès à nos sites en créant un compte professionnel.
Dans le cadre de la refonte de nos plateformes HCP, nous souhaiterions instruire la possibilité de vérifier la réalité de l'existence du professionnel de la santé en nous connectant à votre base de données via API via Gigya

Avez-vous déjà des use case de la sorte SVP ?

Je suis preneuse de toute info, et suis dispo pour un appel à votre convenance ! 😊

Belle journée,

**Comment by zilliw** [comment]
Bonjour,

Tout d'abord merci pour la prise de contact. L'API FHIR est une API REST basée sur les spécifications HL7 FHIR. Nous n'avons pas pour objectif de mettre en place des cas d'usages sur des solutions spécifiques telles que Gigya.

Nous avons par contre des appels API qui pourront vous permettre de récupérer au travers de leurs identifiants RPPS le prénom et nom d'exercice professionnel. Nous n'avons pas aujourd'hui mis en place l'API FHIR Annuaire Santé pour les données restreintes.

Je vous invite à consulter sur le [site suivant ](https://ansforge.github.io/annuaire-sante-fhir-documentation/) les différents cas d'utilisations qui pourront répondre à vos besoins.

Cordialement,

**Comment by zilliw** [comment]
Bonjour,

Je clôture le sujet.

Cordialement.
