### ISSUE TITLE
Accès permanent - comment créer un compte

### ISSUE THREAD

**Issue by def-systemes-fr** [ansforge/annuaire-sante-fhir-documentation#255]
Je suis en mesure d’intégrer l’API dans le logiciel que nous éditons (DEFGEN, logiciel professionnel de génétique), afin de permettre aux praticiens de contrôler la bonne tenue à jour de leur référentiel de contact.
Toutefois, ayant effectué plus de 30 demandes à des fins de mise au point, l’API ne répond plus (bloqué pour 1 ou plusieurs heures...)
Pourriez-vous m’indiquer les conditions d’utilisation de l’API dans un cadre opérationnel ?

**Comment by Tao546127REP** [comment]
> Je suis en mesure d’intégrer l’API dans le logiciel que nous éditons (DEFGEN, logiciel professionnel de génétique), afin de permettre aux praticiens de contrôler la bonne tenue à jour de leur référentiel de contact. Toutefois, ayant effectué plus de 30 demandes à des fins de mise au point, l’API ne répond plus (bloqué pour 1 ou plusieurs heures...) Pourriez-vous m’indiquer les conditions d’utilisation de l’API dans un cadre opérationnel ?


Hey @def-systemes-fr Looks like you're running into some rate limits with the API after making a bunch of requests for DEFGEN. Many APIs have restrictions on how many requests you can make in a certain timeframe to prevent abuse. It’s a good idea to check the API documentation for the specific limits, like the number of requests allowed per minute or hour. If you’re hitting those limits, you might need to implement some sort of throttling in your code or look into whether they offer higher limits for operational use. Let me know if you need help with anything else!

**Comment by def-systemes-fr** [comment]
OK it means that this API cannot be used in a professional environment... I hoped it had a super-user mode so to allow specific registered logins to be used without this limitation.

**Comment by Tao546127REP** [comment]
> OK it means that this API cannot be used in a professional environment... I hoped it had a super-user mode so to allow specific registered logins to be used without this limitation.



Hey @def-systemes-fr Unfortunately, many APIs have usage limitations for security and stability reasons. If super-user access or elevated permissions aren’t available, you might need to explore alternative APIs or services that offer the level of access you require. Additionally, contacting the API provider for potential solutions or workarounds could also be beneficial.
