### ISSUE TITLE
Address.city

### ISSUE THREAD

**Issue by zeoc** [ansforge/annuaire-sante-fhir-documentation#26]
Bonjour,
est-il normal que adress.city d'une organization contienne le code postal en plus de la ville ?
merci

**Comment by nriss** [comment]
Bonjour @zeoc , merci pour la question

Pourriez-vous donner un exemple ?

Je pense que le problème vient de l'implémentation @mchaabaoui

**Comment by mchaabaoui** [comment]
voici un exemple : 
**"city": "06500 MENTON",**
"postalCode": "06500"

On devrait plutôt avoir :

"city": "MENTON",
postalCode": "06500"

@nriss

**Comment by nriss** [comment]
Ok pour moi @mchaabaoui :)

**Comment by mchaabaoui** [comment]
Bonjour @zeoc ,
Merci pour votre feedback. 
il s'agit effectivement  d'un bug qui sera corrigé en conséquence.

**Comment by zeoc** [comment]
Bonjour, avez-vous un ETA pour cette correction ?

**Comment by mchaabaoui** [comment]
Nous travaillons à résoudre ce problème dans la prochaine mise à jour.

**Comment by mchaabaoui** [comment]
L’ANS a été contrainte de mettre à l’arrêt le dispositif agile associé à l’API FHIR au cours du mois d’août 2023. Le dispositif est en cours de reprise. Ainsi, il est pour le moment difficile de prévoir des échéances.

**Comment by mchaabaoui** [comment]
{duplicate](https://github.com/ansforge/annuaire-sante-fhir-serveur/issues/9)
