### ISSUE TITLE
Date diplome

### ISSUE THREAD

**Issue by zeoc** [ansforge/annuaire-sante-fhir-documentation#27]
Bonjour,
existe-t-il un moyen de récupérer la date d'obtention d'un diplome (en acces public) ?
merci

**Comment by mchaabaoui** [comment]
Bonjour @zeoc, merci pour la question.
Serait-il possible de nous exposer votre usecase? pourquoi voulez-vous voir la date de diplôme?
A présent, nos règles de publication des données en libre accès se fondent sur [l’article 5] (https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000046349873) de l’arrêté RPPS et c’est pourquoi on n’a que les informations du diplôme qui sont en accès libre : type, code, libellé. Les autres informations (n°-va disparaître du RPPS-, date et lieu d’obtention) sont en accès restreint.
D'avance merci pour votre retour.

**Comment by zeoc** [comment]
Bonjour,
il s'agit d'un projet de récupération de DATA pour un de nos clients : l'AREDOC. Ils ont actuellement une base interne contenant cette information et souhaitaient pouvoir croiser ces infos avec celle du RPPS.

**Comment by william-ordotype** [comment]
Bonjour, 

Est-ce que le numéro de RPPS ne sera plus accessible depuis l'API de l'annuaire santé ? 

Merci,

**Comment by mchaabaoui** [comment]
Bien reçu @zeoc. 
j'escalade votre demande à nos métiers et juristes pour statuer et reviendrai vers vous dès que j'aurai du  nouveau.

**Comment by mchaabaoui** [comment]
Bonjour @william-ordotype , le numéro RPPS restera accessible depuis l'API, donc pas de changement prévu à cet égard. 
Je n'ai peut-être pas été suffisamment clair en disant ceci (n°-va disparaître du RPPS). il s'agit ici du numéro du diplôme en effet :)

**Comment by mchaabaoui** [comment]
[duplicate](https://github.com/ansforge/annuaire-sante-fhir-serveur/issues/15)
