### ISSUE TITLE
[API] Problème de clé API

### ISSUE THREAD

**Issue by william-ordotype** [ansforge/annuaire-sante-fhir-documentation#32]
Bonjour, 

Depuis ce matin je n'arrive plus à effectuer des requêtes avec ma clé (sur Postman, en http directement, etc.) et lorsque je cherche en générer une nouvelle sur cette page : https://portal.api.esante.gouv.fr/user/login je tombe sur une 404

Merci de votre aide

William

**Comment by mchaabaoui** [comment]
Bonjour @william-ordotype,
Une opération de maintenance est en cours  :   https://status.annuaire-sante.esante.gouv.fr/
Désolé pour la gêne occasionnée.

**Comment by mchaabaoui** [comment]
le service est à nouveau opérationnel.

**Comment by william-ordotype** [comment]
Merci ! je vais m'abonner aux alertes 👍
